--데이터베이스 관리자계정
--SQL주석 이렇게 씁니다.

/* 여러줄 주석
CTRL + / 빠른주석 해제 
*/
--DEPARTMENT_ID FK , EMPLOYEE_ID PK
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

--특정 컬럼만 지정하고 싶으면
SELECT EMPLOYEE_ID, FIRST_NAME, EMAIL FROM EMPLOYEES;

--타입 문자, 날짜는 왼쪽, 숫자는 오른쪽으로 필드값에 나타납니다.

SELECT HIRE_DATE, LAST_NAME, EMPLOYEE_ID FROM EMPLOYEES;

-- 숫자컬럼은 * / + - 가 됩니다.

SELECT FIRST_NAME, SALARY, SALARY + 10000 , SALARY * 0.1 FROM EMPLOYEES;

--NULL값

SELECT COMMISSION_PCT, DEPARTMENT_ID FROM EMPLOYEES;

--컬럼 ALIAS(별칭)

SELECT FIRST_NAME AS 이름, SALARY AS 급여, SALARY + SALARY * 0.1 AS "최종 급여" FROM EMPLOYEES;

--문자열 연결(더하기)
SELECT '이렇게 표현해요' FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME || '님''S의 급여는 ' 
|| SALARY || '$입니다' AS "employee Details" FROM EMPLOYEES;

--DISTINCT 키워드 (중복제거)

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

--세개 컬럼 기준으로 중복 되는행 X
SELECT DISTINCT FIRST_NAME, LAST_NAME,DEPARTMENT_ID FROM EMPLOYEES;
--ROWID(데이터의 주소) ROWNUM(조회된 번호)

SELECT EMPLOYEE_ID , FIRST_NAME , ROWID, ROWNUM FROM EMPLOYEES;



